env:
    credentials: "ENCRYPTED[!7bf2dfa2765dc37bd5a794002c434d44151ee7e06f271131d22b2bbcd9134ff18841a14112e858758f44f9900c95a6b8!]"
    rcloneconfig: "ENCRYPTED[!b1fac849af4fbc211e9372626f1cb6149b51fc96a97a7240053468f1553f60d7b4be7da0c680a4e8871e5578a94cd701!]"
    tokentl: "ENCRYPTED[!28279e8244efba77e4dba5365cbfa3723f617371b50df5abac687ee98c0f154eebde07ca977a22128d56e6fee551ed29!]"
    idtl: "ENCRYPTED[!a2de28cef12fc0da850313d36901c75d8a01ac1f1c1d114c211d091a7a3821445ec9344110bbda3682221a713d02481b!]"
    lunch: lunch qassa_ysl-userdebug
    make: make qassa

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - git config --global user.name "ALprjkt"
       - git config --global user.email "168145100+ALprjkt@users.noreply.github.com"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p ~/ccache
       - rclone copy ysl/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh

  Sync_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start sync qassa Source"
      - mkdir -p ~/rom
      - cd ~/rom
      - sudo curl --create-dirs -L -o /usr/local/bin/repoo -O -L https://storage.googleapis.com/git-repo-downloads/repo
      - sudo chmod a+rx /usr/local/bin/repoo
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/keepQASSA/manifest.git -b Q -g default,-mips,-darwin,-notdefault
      - git clone --depth 1 https://github.com/animelopers/local_manifest.git -b qassa .repo/local_manifests
      - rm -rf .repo/repo && git clone https://gerrit.googlesource.com/git-repo .repo/repo
      - sed -i 's|ssh://git@github.com|https://github.com|g' .repo/manifests/snippets/qassa.xml
#      - repoo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8 --fail-fast
      - repo sync -c -j8 --force-sync --no-clone-bundle --no-tags
      - sed -i 's| -u||g' vendor/qassa/config/branding.mk
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

  Build_script:
      - export BUILD_USERNAME="ALprjkt"
      - export BUILD_HOSTNAME="animelopers"
      - export KBUILD_BUILD_USER="ALprjkt"
      - export KBUILD_BUILD_HOST="animelopers"
#      - export WITH_GAPPS=true
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build qassa for ysl Started!"
      - ./collect.sh
#      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd ~/rom/out/target/product/ysl/ && ls qassa*.zip) Completed!"

  Upload_script:
      - ./upload.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd ~/
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz sagit:qassa -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Ccache Uploaded Successfully!"

